#!/bin/bash

#This script will test if you have internet and will print average ping of $_p{1..X} server.
#If all tests fail it will print KO

#Server who will be pinged.. or not
_p1="cdns.ovh.net"
_p2="www.google.com"
_p3="www.yahoo.com"
_p4="www.facebook.com"

#We ping all the servers (don't forget to modify the for loop if you add a server)
#If the answer isn't found, we don't count this server in order to have a good average.
#We also check if we have a packet loss anywhere

for i in $_p{1..4};
do 
	_cmd=$(ping $i -i 0.2 -c 5)
	_temppa=$(echo -e $_cmd |cut -d '/' -s -f5 |cut -d '.' -f1)
	
	if [ ! -z "$_temppa" ];
	then 
		((j++))
		_pa=$(echo $(($_pa+$_temppa)))
	fi
done

if [ "$_pa" ] && [ "$j" ];
then
	_net=$(echo $(($_pa/$j)))
else
	_net="KO"
fi

if [ ! "$_net" = "KO" ];
then
	echo "$_net" "ms" # Full text
	echo "$_net" "ms" # Short text
else
	echo "KO" # Full text
	echo "KO" # Short text
	echo \#FF0000
fi
